_target_: datamodules.vimeo.VimeoDataModule
data_dir: /data/dataset/vimeo_dataset/vimeo_triplet/
train_batch_size: ${training_loop.train_batch_size}
val_batch_size: ${training_loop.val_batch_size}
num_workers: ${num_workers_per_task}
