_target_: utils.schedulers.LinearRampCosineLR
ramp_len: ${eval:${training_loop.pseudo_epochs}//20} # 5% of training
T_max: ${training_loop.pseudo_epochs}
eta_min: ${eval:${training_loop.learning_rate}//100}
